version: '3.4'

services:
  identity-server-web:
    image: ${DOCKER_REGISTRY}/identity-server-web
    build:
      context: .
      dockerfile: Services/Identity/DeepIn.Identity.Server.Web/Dockerfile

  blobstorage-api:
    image: ${DOCKER_REGISTRY}/blob-storage-api
    build:
      context: .
      dockerfile: Services/BlobStorage/DeepIn.BlobStorage.API/Dockerfile
    depends_on:
      - identity-server-web

  chatting-api:
    image: ${DOCKER_REGISTRY}/chatting-api
    build:
      context: .
      dockerfile: Services/Chatting/DeepIn.Chatting.API/Dockerfile
    depends_on:
      - identity-server-web

  chatting-signalrhub:
    image: ${DOCKER_REGISTRY}/chatting-signalr-hub
    build:
      context: .
      dockerfile: Services/Chatting/DeepIn.Chatting.SignalrHub/Dockerfile
    depends_on:
      - identity-server-web

  contacts-api:
    image: ${DOCKER_REGISTRY}/contacts-api
    build:
      context: .
      dockerfile: Services/Contacts/DeepIn.Contacts.API/Dockerfile
    depends_on:
      - identity-server-web

  emailing-api:
    image: ${DOCKER_REGISTRY}/emailing-api
    build:
      context: .
      dockerfile: Services/Emailing/DeepIn.Emailing.API/Dockerfile
    depends_on:
      - identity-server-web

  identity-api:
    image: ${DOCKER_REGISTRY}/identity-api
    build:
      context: .
      dockerfile: Services/Identity/DeepIn.Identity.API/Dockerfile
    depends_on:
      - identity-server-web

  identity-server-api:
    image: ${DOCKER_REGISTRY}/identity-server-api
    build:
      context: .
      dockerfile: Services/Identity/DeepIn.Identity.Server.API/Dockerfile
    depends_on:
      - identity-server-web

  messaging-api:
    image: ${DOCKER_REGISTRY}/messaging-api
    build:
      context: .
      dockerfile: Services/Messaging/DeepIn.Messaging.API/Dockerfile
    depends_on:
      - identity-server-web

  web-chat-http-aggregator:
    image: ${DOCKER_REGISTRY}/web-chat-http-aggregator
    build:
      context: .
      dockerfile: ApiGateways/Bff/DeepIn.WebChat.HttpAggregator/Dockerfile
    depends_on:
      - identity-server-web

  web-chat-api-gw:
    image: envoyproxy/envoy:v1.25-latest