version: '3.4'

services:
  webspa.httpaggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  emailing.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  messaging.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  identity.server.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  identity.server.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  contacts.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  chatting.signalrhub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  chatting.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  blobstorage.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
